### ISSUE TITLE
Removing {[type]} & return

### ISSUE THREAD

**Issue by ColonelBundy** [nikhilkalige/docblockr#157]
Sometimes I document what the function actually does in the function description and I don't need to specify the type of the param or the return, Option to remove this and just keep the name?

Also removing the @return if there's no return found within the function brackets?

Also automatic function description would be wonderful like:

```
function test(a, b, c) {
}
```

Would turn into:

```
/**
   * test
   * @param  a
   * @param  b
   * @param  c
   */
```

**Comment by julmot** [comment]
:+1: for detecting if there is any `return`

**Comment by MoritzKn** [comment]
Unfortunately detecting if there is a `return` isn't feasible with the current setup since all parsing is baed on regexes and for that the would need something more sophisticated. The type is part of jsDoc and I don't think it's a good idea to add it sometime and sometime not. However #312 address something similar from the perspective of flowtype which I think makes more sense. Closing in favor of this issue.
