### ISSUE TITLE
Function parameters are not automatically added

### ISSUE THREAD

**Issue by ghost** [nikhilkalige/docblockr#167]
```
/**
function test (a, b) {}
```
will simply return

```
/**
 * 
 */
function test (a, b) {}
```

**Comment by loki0609** [comment]
Seeing the same thing:
Windows, atom 1.5.4, docblockr 0.7.3

**Comment by Michael-Thibault** [comment]
I've been seeing the same thing recently. Docblockr **was** working before, so I'm at a loss as to what's changed and is causing the issue.

OS X 10.10.5 and 10.11.3, Atom 1.5.3, docblockr 0.7.3

**Comment by whyhankee** [comment]
I still have the same as @4Digits 

OSX 10.11.3
Atom 1.6.0
DocBlockr 0.7.3


/**<tab>
 * 
 */
function test (a, b) {
}

A friend of mine (same versions) does not have this problem ?!

I'm not really an Atom expert but is there something I can do to help?

**Comment by billymedia** [comment]
Im also seeing the same thing when trying in php files.

**Comment by ssnepenthe** [comment]
It seems to me that this might be caused by some sort of conflict with the core `language-*` packages over the `tab` key.

I am not running into this issue when using `enter`, only when using `tab`.

So for example (with no 3rd party packages except for docblockr):

```
<?php

/**<tab>
function apples( $bananas ) {}
```

Results in:

```
<?php

/**
 *
 */
function apples( $bananas ) {}
```

However:

```
<?php

/**<enter>
function apples( $bananas ) {}
```

Results in what you are expecting:

```
<?php

/**
 * [apples description]
 * @param  [type] $bananas [description]
 * @return [type]          [description]
 */
function apples( $bananas ) {}
```

But if you disable the language-specific features, for example by removing the opening `<?php` tag, dropping the `.php` extension or disabling the `language-php` package, both `enter` and `tab` work as they are supposed to.

The same goes for `.js` files and the `language-javascript` package.

Docblockr v0.7.3
Atom v1.7.1
Mac OS X v10.11.4

**Comment by loki0609** [comment]
Enter works for me. I guess i was just doing tab

**Comment by whyhankee** [comment]
Enter works for me as well, might be something to document though.

**Comment by errskipower** [comment]
I'm seeing the same thing.  `<Enter>` works, but `<tab>` does not.

Docblockr v0.7.3
Atom v1.8.0 Beta 4
Mac OSX v10.11.4

**Comment by VesterDe** [comment]
Seeing the same thing.

Docblockr v0.7.3
Atom v1.8.0 Beta 3
Arch Linux

**Comment by MoritzKn** [comment]
I've investigated this behavior and found the problem:
Wenn pressing tab the command `snippets:expand` will be executed. This event is specified in the [snippets keymap][keymap] with the exact same selector as the `docblockr:parse-tab` event. If the language package of the open file does not specify an `/**` snippet, like [PHP][phpsnippet] does, this is not a problem because in this case the [snippets package calls the `.abortKeyBinding()` function][abort] and, because of an [cascade][cascade], `docblockr:parse-tab` will be executed. This is the reason, why this behavior is reproducable in JavaScript and PHP but not Java.

To fix this problem we  should make the selector for the `docblockr:parse-tab` event more specific.

[keymap]: https://github.com/atom/snippets/blob/master/keymaps/snippets-1.cson
[phpsnippet]: https://github.com/atom/language-php/blob/master/snippets/language-php.cson#L20
[abort]: https://github.com/atom/snippets/blob/master/lib/snippets.coffee#L38
[cascade]: http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#overloading-key-bindings
