### ISSUE TITLE
double line issue

### ISSUE THREAD

**Issue by julmot** [nikhilkalige/docblockr#194]
Since today I have the following issue:

When pressing enter two new lines will be created within a comment. 
Let's say you're creating a new comment. The the following will come up:

```javascript
    /**
     *
     * [cursor]
     */
```

What I expect:

```javascript
    /**
     * [cursor]
     */
```

Same for `//`.

**Comment by clayfreeman** [comment]
It seems like Atom's "enter" key event isn't being cancelled after triggering Docblockr.

**Comment by nikhilkalige** [comment]
![1470158003868](https://cloud.githubusercontent.com/assets/1267404/17337987/2ae652b2-589a-11e6-852f-022ebed86cd5.gif)
Cant seem to reproduce it..

**Comment by clayfreeman** [comment]
<img src="http://d.pr/i/tcO3/14ZHxmPX+"/>

This is what happens for me.

**Comment by nikhilkalige** [comment]
@clayfreeman  is that java?

**Comment by jeremyvii** [comment]
I am in the same room as @clayfreeman and I am not having the same problem but I am on windows. Is it a mac issue?

**Comment by clayfreeman** [comment]
@nikhilkalige No, C++

**Comment by nikhilkalige** [comment]
```
void asdf() {
  
};
/**
 * 
 */
//
//
struct melvin_data_t {
  int value = 16;
}
```

:( . This doesn't make sense at all.. I think there may be some package collision

**Comment by clayfreeman** [comment]
I disabled all my community extensions and re-enabled them and now it's working as expected. Weird!

**Comment by MoritzKn** [comment]
As @nikhilkalige already pointed out this seams to happen due to a collision of two keybindings. You can debug this kind of problems using the [Keybinding Resolver](https://atom.io/packages/keybinding-resolver) (ctrl-.). This way you can find out what keybinding causes the problem and [change or remove](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) the keybinding.
I guess if both keybindings have the same selector, atom determines which one to use by the order you installed the packege that added the keybinding. This could explain why disabling and again enabling solved the problem for @clayfreeman.

**Comment by mattweir10** [comment]
I have this same problem for Javascript on OS X. Pressing enter inside a block produces the equivalent of pressing enter 3 times. I don't think I have an conflicts here, rather the 3 new lines are the result of docblockr, then the base atom action, then the core OS X action.

`/** <enter>` results in:

```
/**
 *
 *
 * 
 */
```
Here's my keybinding resolver from this action:
![docblockr_issue](https://cloud.githubusercontent.com/assets/902096/17345046/2f351366-58b9-11e6-8abe-a50d74d9a6ff.png)

Seems like docblockr isn't eating the enter keypress here.

**Comment by MoritzKn** [comment]
At least in @mattweir10's example the events seam fine. The `docblockr:parse-enter` command is the only used command. `editor:newline` has a matching selector, but is not applied  because `docblockr:parse-enter` comes first.

Dose this only happen with if you press `/** `<kbd>enter</kbd> or even if you press `/** `<kbd>tab</kbd>?

**Comment by nikhilkalige** [comment]
By looking at the image that's what I thought too. But I just cannot reproduce the same error

**Comment by MoritzKn** [comment]
On my GNU/Linux computer I can't reproduce it too. I guess it really is a OSX only issue.

**Comment by julmot** [comment]
@MoritzKn Nope, I'm using Windows 7.

**Comment by julmot** [comment]
For some reason it was solved for me today, didn't updated something manually. Feel free to reopen if you still experience this issue.
