### ISSUE TITLE
Enter/Return key does not trigger expansion in PHP files

### ISSUE THREAD

**Issue by montchr** [nikhilkalige/docblockr#213]
If I start typing `/**` and then press return, a docblock-style comment is not created and I get the following:

```
/**

```

If I use the tab key instead, the expansion of the comment is successful.

This only occurs in PHP files — I've tested in JS and SCSS files as well. I've disabled all other plugins and the issue still happens.

**Comment by MoritzKn** [comment]
I can't reproduce this..
Could you please try these two things::
1. Use the [keybinding-resolver](https://atom.io/packages/keybinding-resolver) to find out which commad is executet if you press enter
2. Press <kbd>cmd-p</kbd> and select `docblockr:parse-enter` instead of directly pressing <kbd>enter</kbd>

**Comment by MoritzKn** [comment]
No response, closing. Feel free to comment here if it's still an issue.
