### ISSUE TITLE
C language support

### ISSUE THREAD

**Issue by piyushdivyankar1994** [nikhilkalige/docblockr#215]
variable isn't documented in C. 
structures aren't documented like functions(I don't know if this functionality is there already, if it is then please point it out to me)

**Comment by MoritzKn** [comment]
At the moment Docblockr don't support autocompletion for struct, classes and structures alike -- in every language. This could be implemented, but I have no time for this at the moment and I don't think any of the other contributors have. However if someone is interested in doing so, I would be happy to help.
Adding support for variables seems like an easy task for me: CppParser.prototype.parse_var has to be replaced with an actual parser, which can probably be done with a Regex.
If you are interesting in filing a PR, go ahead. Otherwise I will probably do it, but that could take a bit.

**Comment by piyushdivyankar1994** [comment]
Thanks for the reply.
I would love to do this but I am unfamiliar with javascript. Maybe I will pick it up in future(uncertain).

**Comment by MoritzKn** [comment]
I actual started to implement this and wrote a parser for C variable declarations. But I noticed that autocompletion for this don't seems to make any sense. There is nothing like `@param` or `@return` for a variable. Same thing for structs.
But maybe I am overlooking something. What's your opinion on that, what would you expect to see in the autocompletion?

**Comment by piyushdivyankar1994** [comment]
I my opinion for a variable no new features are needed. For structs and classes it would be good to have snippets. For example look at the following struct that i have documented. 
`/**
 * This structure is used to represent 3D millier indices of points in real space
 * of the crystal lattice.
 * \struct point3D
 * \typedef point3D
 * \author Piyush Divyankar
 */
struct point3D
{
    /** x-coordinate */
    float x;
    /** y-coordinate */
    float y;
    /** z-coordinate */
    float z;
} typedef point3D;`

Is it possible to make it look more like the function snippet. I don't know if it is possible to document members outside the class, however typedef, struct etc can be outside. If it is possible to document members outside then this would be great.

**Comment by MoritzKn** [comment]
> I don't know if it is possible to document members outside the class, however typedef, struct etc can be outside. If it is possible to document members outside then this would be great.
Honestly I don't know what you mean with that. Could you further explain that and/or give an example?

**Comment by MoritzKn** [comment]
No response, closing. Feel free to comment here if it's still an issue.
