### ISSUE TITLE
@param and @return not showing up in tooltip documentation

### ISSUE THREAD

**Issue by gajdot** [nikhilkalige/docblockr#265]
When creating a documentation for TypeScript the auto generated @params are generated correctly, but even after completing them it won't show up in the tool-tip no matter what. 

Is should show below the main description ever @param and @return description

![untitled](https://cloud.githubusercontent.com/assets/8439590/25939989/57177ba0-363d-11e7-8879-28eac6778f76.png)

**Comment by MoritzKn** [comment]
Docblockr only generates the comment. This tool-tip has to come from another package. It seems like the typescript package [has such a feature](https://github.com/TypeStrong/atom-typescript#features), so that is probably the package in question. However if the generated comment is just wrong, this is something docblockr could fix. Maybe the `{String}` part is the problem..
In that case, this is basically a duplicate of #134.

**Comment by gajdot** [comment]
As long as the comment starts with a @ character it's not showing up in the tool-tip and it's not recognized as input documentation.

**Comment by MoritzKn** [comment]
In this case this really seams like an issue with [TypeStrong/atom-typescript](https://github.com/TypeStrong/atom-typescript) or maybe the typescript language server. Please file an issue there.
